springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    title: Kafka Consumer API
spring:
  kafka:
    bootstrap-servers: 172.17.0.1:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: health, info
